In [1]:
import pandas

data = pandas.read_csv("datasets/pima_indians.csv")
data

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age,Outcome
0,6,148,72,35,0,33.6,50,Likely to Have Diabetes
1,1,85,66,29,0,26.6,31,No Diabetes
2,8,183,64,0,0,23.3,32,Likely to Have Diabetes
3,1,89,66,23,94,28.1,21,No Diabetes
4,0,137,40,35,168,43.1,33,Likely to Have Diabetes
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,63,No Diabetes
764,2,122,70,27,0,36.8,27,No Diabetes
765,5,121,72,23,112,26.2,30,No Diabetes
766,1,126,60,0,0,30.1,47,Likely to Have Diabetes
767,1,93,70,31,0,30.4,23,No Diabetes

In [2]:
# describe the data
data.describe()

,Number Children,Glucose,BloodPressure,SkinThickness,Insulin,BMI,Age
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,33.240885
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,11.760232
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,24.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,29.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,41.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,81.000000

In [3]:
# separate the data
array = data.values
# print(array)

X=array[:, 0:7]
# print(X)
Y = array[:, 7]
print(Y)

['Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes']

In [4]:
# We split the data even further
from sklearn import model_selection
X_train,X_test,Y_train,Y_test = model_selection.train_test_split(X,Y,test_size=0.3, random_state=42)

In [5]:
# import one of the models
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,Y_train)

SVC()

In [6]:
# Test the model
predictions = model.predict(X_test)
print("Model predicted: ", predictions)
print("We expected: ", Y_test)

Model predicted:  ['No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes']
We expected:  ['No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'Likely to Have Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes'
 'No Diabetes' 'No Diabetes' 'Likely to Have Diabetes'
 'Likely to Have Diabetes' 'No Diabetes' 'No Diabetes' 'No Diabetes']

In [7]:
# Test the accuracy score of the model
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(Y_test, predictions))

Accuracy:  0.7359307359307359

In [ ]:
outcome = [[4, 13 , 98, 0, 14, 7, 42]]
outcome = model.predict(outcome)
print("You have ", outcome)

You will be having a ['No Diabetes']